backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

locale: 'ar'

collections:
  - name: "tours"
    label: "الرحلات"
    folder: "content/tours"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "الصورة الرئيسية", name: "image", widget: "image"}
      - {label: "السعر", name: "price", widget: "number"}
      - {label: "سعر الخصم (اختياري)", name: "discountPrice", widget: "number", required: false}
      - {label: "المدة", name: "duration", widget: "string"}
      - {label: "الموقع", name: "location", widget: "string"}
      - {label: "التصنيف", name: "category", widget: "select", options: ["ثقافية", "شاطئية", "مغامرات", "رومانسية", "تسوق", "عائلية"]}
      - {label: "التقييم", name: "rating", widget: "number", value_type: "float", min: 0, max: 5, step: 0.1}
      - {label: "عدد التقييمات", name: "reviewsCount", widget: "number"}
      - {label: "الوصف", name: "description", widget: "text"}
      - label: "برنامج الرحلة"
        name: "itinerary"
        widget: "list"
        fields:
          - {label: "اليوم", name: "day", widget: "string"}
          - {label: "العنوان", name: "title", widget: "string"}
          - {label: "الوصف", name: "description", widget: "text"}
      - label: "ما يشمله السعر"
        name: "includes"
        widget: "list"
      - label: "ما لا يشمله السعر"
        name: "excludes"
        widget: "list"
      - label: "معرض الصور"
        name: "gallery"
        widget: "list"
        field: {label: "صورة", name: "image", widget: "image"}
      - label: "التقييمات"
        name: "reviews"
        widget: "list"
        fields:
          - {label: "الاسم", name: "name", widget: "string"}
          - {label: "الصورة", name: "image", widget: "image"}
          - {label: "التاريخ", name: "date", widget: "string"}
          - {label: "التقييم", name: "rating", widget: "number", value_type: "float", min: 0, max: 5, step: 0.1}
          - {label: "التعليق", name: "comment", widget: "text"}

  - name: "destinations"
    label: "الوجهات"
    folder: "content/destinations"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "الاسم", name: "name", widget: "string"}
      - {label: "الصورة", name: "image", widget: "image"}
      - {label: "الوصف", name: "description", widget: "text"}
      - {label: "عدد الرحلات", name: "tours", widget: "number"}
      - {label: "الدولة", name: "country", widget: "string"}
      - {label: "أفضل وقت للزيارة", name: "bestTime", widget: "string"}
      - {label: "القارة", name: "continent", widget: "select", options: ["آسيا", "أوروبا", "أفريقيا", "أمريكا الشمالية", "أمريكا الجنوبية", "أستراليا"]}

  - name: "blog"
    label: "المدونة"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "الصورة", name: "image", widget: "image"}
      - {label: "مقتطف", name: "excerpt", widget: "text"}
      - {label: "التاريخ", name: "date", widget: "datetime"}
      - {label: "الكاتب", name: "author", widget: "string"}
      - {label: "صورة الكاتب", name: "authorImage", widget: "image"}
      - {label: "التصنيف", name: "category", widget: "select", options: ["نصائح سفر", "تجارب سفر", "طعام وثقافة", "إقامة"]}
      - {label: "الوسوم", name: "tags", widget: "list"}
      - {label: "المحتوى", name: "body", widget: "markdown"}

  - name: "gallery"
    label: "معرض الصور"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "الصورة", name: "src", widget: "image"}
      - {label: "التصنيف", name: "category", widget: "select", options: ["وجهات سياحية", "فنادق", "أنشطة", "طبيعة"]}

  - name: "team"
    label: "فريق العمل"
    folder: "content/team"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "الاسم", name: "name", widget: "string"}
      - {label: "المنصب", name: "position", widget: "string"}
      - {label: "الصورة", name: "image", widget: "image"}
      - {label: "السيرة الذاتية", name: "bio", widget: "text"}

  - name: "settings"
    label: "إعدادات الموقع"
    files:
      - file: "content/settings/general.json"
        label: "الإعدادات العامة"
        name: "general"
        fields:
          - {label: "اسم الموقع", name: "siteName", widget: "string"}
          - {label: "شعار الموقع", name: "logo", widget: "image"}
          - {label: "وصف الموقع", name: "description", widget: "text"}
          - {label: "البريد الإلكتروني", name: "email", widget: "string"}
          - {label: "رقم الهاتف", name: "phone", widget: "string"}
          - {label: "العنوان", name: "address", widget: "text"}
          - label: "روابط التواصل الاجتماعي"
            name: "socialLinks"
            widget: "list"
            fields:
              - {label: "المنصة", name: "platform", widget: "select", options: ["facebook", "twitter", "instagram", "youtube", "linkedin"]}
              - {label: "الرابط", name: "url", widget: "string"}
      
      - file: "content/settings/home.json"
        label: "الصفحة الرئيسية"
        name: "home"
        fields:
          - {label: "عنوان الترحيب", name: "heroTitle", widget: "string"}
          - {label: "نص الترحيب", name: "heroText", widget: "text"}
          - {label: "صورة الخلفية", name: "heroImage", widget: "image"}
          - label: "الوجهات المميزة"
            name: "featuredDestinations"
            widget: "list"
            fields:
              - {label: "الاسم", name: "name", widget: "string"}
              - {label: "الصورة", name: "image", widget: "image"}
              - {label: "الرابط", name: "link", widget: "string"}
          - label: "لماذا تختارنا"
            name: "whyChooseUs"
            widget: "list"
            fields:
              - {label: "العنوان", name: "title", widget: "string"}
              - {label: "الوصف", name: "description", widget: "text"}
              - {label: "الأيقونة", name: "icon", widget: "string"}
